deployment:
  tasks:
    - export DEPLOYPATH=/home/artnshin/public_html/sendcraft
    - /bin/cp -R * $DEPLOYPATH
    - cd $DEPLOYPATH && source /home/artnshin/virtualenv/sendcraft/3.9/bin/activate && pip install -r requirements.txt
