---
deployment:
  tasks:
    # Deploy files to correct Python app location (NOT public_html)
    - export DEPLOYPATH=/home/artnshin/sendcraft
    - /bin/cp -R * $DEPLOYPATH
    
    # Install dependencies with correct virtualenv path  
    - cd $DEPLOYPATH
    - /home/artnshin/virtualenv/sendcraft/3.9/bin/pip install -r requirements.txt
    
    # Set permissions for Python app files
    - chmod +x $DEPLOYPATH/app.py
    - chmod +x $DEPLOYPATH/passenger_wsgi.py
    
    # Create logs directory
    - mkdir -p /home/artnshin/logs
    
    # Restart Python app
    - touch $DEPLOYPATH/tmp/restart.txt