"""Phase 9.1: Initial IMAP backend migration

Revision ID: bf2cb09a5e04
Revises: 
Create Date: 2025-10-22 01:38:26.761566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf2cb09a5e04'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_inbox',
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.String(length=500), nullable=True),
    sa.Column('uid', sa.String(length=100), nullable=True),
    sa.Column('from_address', sa.String(length=200), nullable=False),
    sa.Column('from_name', sa.String(length=200), nullable=True),
    sa.Column('to_address', sa.Text(), nullable=True),
    sa.Column('cc_addresses', sa.Text(), nullable=True),
    sa.Column('bcc_addresses', sa.Text(), nullable=True),
    sa.Column('reply_to', sa.String(length=200), nullable=True),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('body_text', sa.Text(), nullable=True),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('is_flagged', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('is_answered', sa.Boolean(), nullable=False),
    sa.Column('is_draft', sa.Boolean(), nullable=False),
    sa.Column('has_attachments', sa.Boolean(), nullable=False),
    sa.Column('attachments_json', sa.Text(), nullable=True),
    sa.Column('attachment_count', sa.Integer(), nullable=True),
    sa.Column('raw_headers', sa.Text(), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('thread_id', sa.String(length=200), nullable=True),
    sa.Column('in_reply_to', sa.String(length=500), nullable=True),
    sa.Column('references', sa.Text(), nullable=True),
    sa.Column('folder', sa.String(length=100), nullable=True),
    sa.Column('labels', sa.Text(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['email_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('email_inbox', schema=None) as batch_op:
        batch_op.create_index('idx_account_folder', ['account_id', 'folder'], unique=False)
        batch_op.create_index('idx_account_read', ['account_id', 'is_read'], unique=False)
        batch_op.create_index('idx_account_received', ['account_id', 'received_at'], unique=False)
        batch_op.create_index('idx_account_thread', ['account_id', 'thread_id'], unique=False)
        batch_op.create_index('idx_message_unique', ['account_id', 'message_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_email_inbox_folder'), ['folder'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_inbox_from_address'), ['from_address'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_inbox_has_attachments'), ['has_attachments'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_inbox_is_read'), ['is_read'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_inbox_message_id'), ['message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_inbox_received_at'), ['received_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_inbox_subject'), ['subject'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_inbox_thread_id'), ['thread_id'], unique=False)

    with op.batch_alter_table('email_accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imap_server', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('imap_port', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('imap_use_ssl', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('imap_use_tls', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('last_sync', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('auto_sync_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('sync_interval_minutes', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_accounts', schema=None) as batch_op:
        batch_op.drop_column('sync_interval_minutes')
        batch_op.drop_column('auto_sync_enabled')
        batch_op.drop_column('last_sync')
        batch_op.drop_column('imap_use_tls')
        batch_op.drop_column('imap_use_ssl')
        batch_op.drop_column('imap_port')
        batch_op.drop_column('imap_server')

    with op.batch_alter_table('email_inbox', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_inbox_thread_id'))
        batch_op.drop_index(batch_op.f('ix_email_inbox_subject'))
        batch_op.drop_index(batch_op.f('ix_email_inbox_received_at'))
        batch_op.drop_index(batch_op.f('ix_email_inbox_message_id'))
        batch_op.drop_index(batch_op.f('ix_email_inbox_is_read'))
        batch_op.drop_index(batch_op.f('ix_email_inbox_has_attachments'))
        batch_op.drop_index(batch_op.f('ix_email_inbox_from_address'))
        batch_op.drop_index(batch_op.f('ix_email_inbox_folder'))
        batch_op.drop_index('idx_message_unique')
        batch_op.drop_index('idx_account_thread')
        batch_op.drop_index('idx_account_received')
        batch_op.drop_index('idx_account_read')
        batch_op.drop_index('idx_account_folder')

    op.drop_table('email_inbox')
    # ### end Alembic commands ###
