"""Add autosync_config table

Revision ID: d5b672b7cb54
Revises: bf2cb09a5e04
Create Date: 2025-11-05 15:21:25.718350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5b672b7cb54'
down_revision = 'bf2cb09a5e04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('autosync_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('sync_interval_minutes', sa.Integer(), nullable=False),
    sa.Column('limit_per_sync', sa.Integer(), nullable=False),
    sa.Column('full_sync', sa.Boolean(), nullable=False),
    sa.Column('folder', sa.String(length=100), nullable=False),
    sa.Column('sync_only_unread', sa.Boolean(), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('last_sync_status', sa.String(length=20), nullable=True),
    sa.Column('last_sync_message', sa.Text(), nullable=True),
    sa.Column('last_synced_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['email_accounts.id'], ),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('autosync_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_autosync_configs_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_autosync_configs_domain_id'), ['domain_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('autosync_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_autosync_configs_domain_id'))
        batch_op.drop_index(batch_op.f('ix_autosync_configs_account_id'))

    op.drop_table('autosync_configs')
    # ### end Alembic commands ###
